spring.application.name=WindFarm-Backend
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_db
spring.datasource.username=postgres
spring.datasource.password=4523
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
