version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: windfarm_db
    environment:
      POSTGRES_DB: ecommerce_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4523
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - windfarm_network
    restart: unless-stopped

  backend:
    build: .
    container_name: windfarm_backend
    depends_on:
      - db
    environment:
      - DB_NEON_URL=localhost
      - DB_USER=postgre
      - DB_PASS=4523
      - SEED_DB=true
    ports:
      - "8080:8080"
    networks:
      - windfarm_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  windfarm_network:
    driver: bridge